doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        entity_managers:
            vouchers:
                mappings:
                    Voucher:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Modules/Voucher/Persistence/Entity'
                        prefix: 'App\Modules\Voucher\Persistence\Entity'
                        alias: Voucher
                    Security:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Modules/Security/Persistence/Entity'
                        prefix: 'App\Modules\Security\Persistence\Entity'
                        alias: Security

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
